apiVersion: apps/v1
kind: Deployment
metadata:
  name: ats-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ats-app
  template:
    metadata:
      labels:
        app: ats-app
    spec:
      containers:
      - name: ats-app
        image: atsregistry1994.azurecr.io/ats-app:v1
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ats-service
spec:
  type: LoadBalancer
  selector:
    app: ats-app
  ports:
  - port: 80
    targetPort: 8501